{
  "openapi": "3.1.0",
  "info": {
    "title": "AI Gateway",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/api/v1/upload": {
      "post": {
        "summary": "上传文件",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Agent",
            "in": "header",
            "description": "",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "description": "需要上传的文件",
                    "example": "file:///Users/liueic/Downloads/607a919df57e2a8b6a7ab17022cdf663122166603.jpg",
                    "type": "string",
                    "format": "binary"
                  },
                  "created_by": {
                    "description": "文件名",
                    "example": "xiaoming",
                    "type": "string"
                  }
                },
                "required": [
                  "file",
                  "created_by"
                ]
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "title": "响应码"
                    },
                    "msg": {
                      "type": "string",
                      "title": "响应字段"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "title": "响应URL"
                        },
                        "name": {
                          "type": "string",
                          "title": "文件名"
                        },
                        "size": {
                          "type": "integer",
                          "title": "文件大小"
                        },
                        "extension": {
                          "type": "string",
                          "title": "拓展名"
                        },
                        "mime_type": {
                          "type": "string",
                          "title": "文件mine类型"
                        },
                        "created_by": {
                          "type": "string",
                          "title": "创建用户"
                        },
                        "created_at": {
                          "type": "integer",
                          "title": "创建时间"
                        }
                      },
                      "required": [
                        "id",
                        "name",
                        "size",
                        "extension",
                        "mime_type",
                        "created_by",
                        "created_at"
                      ],
                      "title": "信息"
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ]
                },
                "example": {
                  "code": 200,
                  "msg": "File uploaded successfully",
                  "data": {
                    "id": "https://s3.juniortree.com/xiao-x-bao/uploads/2025/09/01/b9cb193906b145939dc3d9cb6240b933.jpg",
                    "name": "607a919df57e2a8b6a7ab17022cdf663122166603.jpg",
                    "size": 348514,
                    "extension": "jpg",
                    "mime_type": "image/jpeg",
                    "created_by": "xiaoming",
                    "created_at": 1756713029
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/agents": {
      "get": {
        "summary": "查询可用Agent",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "title": "是否成功"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "total": {
                          "type": "integer",
                          "title": "启用Agent数量",
                          "description": "当前注册的Agent数量"
                        },
                        "agents": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "name": {
                                "type": "string",
                                "title": "Agent名",
                                "description": "当前的Agent名"
                              },
                              "type": {
                                "type": "string",
                                "title": "类型"
                              },
                              "module": {
                                "type": "string",
                                "title": "后端注册的model"
                              },
                              "capabilities": {
                                "type": "object",
                                "properties": {
                                  "streaming": {
                                    "type": "boolean"
                                  },
                                  "file_upload": {
                                    "type": "boolean"
                                  }
                                },
                                "required": [
                                  "streaming",
                                  "file_upload"
                                ],
                                "title": "支持类型",
                                "description": "是否支持流式、文件上传"
                              }
                            },
                            "required": [
                              "name",
                              "type",
                              "module",
                              "capabilities"
                            ]
                          },
                          "title": "Agent"
                        }
                      },
                      "required": [
                        "total",
                        "agents"
                      ],
                      "title": "响应体"
                    }
                  },
                  "required": [
                    "success",
                    "data"
                  ]
                },
                "example": {
                  "success": true,
                  "data": {
                    "total": 2,
                    "agents": [
                      {
                        "name": "dify",
                        "type": "DifyAgent",
                        "module": "agent.dify",
                        "capabilities": {
                          "streaming": true,
                          "file_upload": true
                        }
                      },
                      {
                        "name": "fastgpt",
                        "type": "FastGPTAgent",
                        "module": "agent.fastgpt",
                        "capabilities": {
                          "streaming": true,
                          "file_upload": true
                        }
                      }
                    ]
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/agents/{name}": {
      "get": {
        "summary": "获取指定Agent信息",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "name",
            "in": "path",
            "description": "",
            "required": true,
            "example": "fastgpt",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "type": {
                          "type": "string"
                        },
                        "module": {
                          "type": "string"
                        },
                        "capabilities": {
                          "type": "object",
                          "properties": {
                            "streaming": {
                              "type": "boolean"
                            },
                            "file_upload": {
                              "type": "boolean"
                            }
                          },
                          "required": [
                            "streaming",
                            "file_upload"
                          ]
                        }
                      },
                      "required": [
                        "name",
                        "type",
                        "module",
                        "capabilities"
                      ]
                    }
                  },
                  "required": [
                    "success",
                    "data"
                  ]
                },
                "example": {
                  "success": true,
                  "data": {
                    "name": "fastgpt",
                    "type": "FastGPTAgent",
                    "module": "agent.fastgpt",
                    "capabilities": {
                      "streaming": true,
                      "file_upload": true
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/agents/{agent}/health": {
      "get": {
        "summary": "获取Agent健康状况",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "agent",
            "in": "path",
            "description": "查询的Agent",
            "required": true,
            "example": "fastgpt",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "title": "状态",
                      "description": "当前成功状态"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "title": "Agent",
                          "description": "当前检查Agent名称"
                        },
                        "status": {
                          "type": "string",
                          "title": "状态",
                          "description": "当前Agent状态"
                        },
                        "timestamp": {
                          "type": "number",
                          "title": "时间戳",
                          "description": "当前时间戳"
                        },
                        "capabilities": {
                          "type": "object",
                          "properties": {
                            "streaming": {
                              "type": "boolean",
                              "title": "流式"
                            },
                            "file_upload": {
                              "type": "boolean",
                              "title": "文件传输"
                            }
                          },
                          "required": [
                            "streaming",
                            "file_upload"
                          ],
                          "title": "能力",
                          "description": "是否支持流式或者文件上传"
                        }
                      },
                      "required": [
                        "name",
                        "status",
                        "timestamp",
                        "capabilities"
                      ]
                    }
                  },
                  "required": [
                    "success",
                    "data"
                  ]
                },
                "example": {
                  "success": true,
                  "data": {
                    "name": "fastgpt",
                    "status": "healthy",
                    "timestamp": 1756781459.063165,
                    "capabilities": {
                      "streaming": true,
                      "file_upload": true
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/auth/login": {
      "post": {
        "summary": "用户登陆",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "title": "文件名"
                  },
                  "password": {
                    "type": "string",
                    "title": "密码"
                  }
                },
                "required": [
                  "username",
                  "password"
                ]
              },
              "example": {
                "username": "your_username",
                "password": "your_password"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "access_token": {
                      "type": "string",
                      "title": "jwt",
                      "description": "生成的jwt密钥"
                    },
                    "token_type": {
                      "type": "string"
                    },
                    "expires_in": {
                      "type": "integer",
                      "title": "过期时间"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "username": {
                          "type": "string",
                          "title": "用户名"
                        },
                        "email": {
                          "type": "string",
                          "title": "邮件"
                        },
                        "full_name": {
                          "type": "string",
                          "title": "用户完整名"
                        },
                        "role": {
                          "type": "string",
                          "title": "角色"
                        },
                        "status": {
                          "type": "string",
                          "title": "状态"
                        },
                        "id": {
                          "type": "string",
                          "title": "用户ID"
                        },
                        "created_at": {
                          "type": "string",
                          "title": "创建时间戳"
                        },
                        "updated_at": {
                          "type": "string",
                          "title": "上次更新用户时间"
                        },
                        "last_login": {
                          "type": "string",
                          "title": "上次登录时间"
                        },
                        "api_calls_count": {
                          "type": "integer",
                          "title": "调用API次数"
                        },
                        "max_api_calls": {
                          "type": "integer",
                          "title": "最大调用API次数"
                        }
                      },
                      "required": [
                        "username",
                        "email",
                        "full_name",
                        "role",
                        "status",
                        "id",
                        "created_at",
                        "updated_at",
                        "last_login",
                        "api_calls_count",
                        "max_api_calls"
                      ],
                      "title": "用户的相关信息"
                    }
                  },
                  "required": [
                    "access_token",
                    "token_type",
                    "expires_in",
                    "user"
                  ]
                },
                "example": {
                  "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc1NjkwMDc0N30.2D3oUBdsypiLBGPG7qCBbKK1lBnJH8JpvtnF6MNpyNk",
                  "token_type": "bearer",
                  "expires_in": 1800,
                  "user": {
                    "username": "admin",
                    "email": "admin@pancrepal.com",
                    "full_name": "系统管理员",
                    "role": "admin",
                    "status": "active",
                    "id": "68b69f1367bdaff96386c4e6",
                    "created_at": "2025-09-02T07:38:59.194000",
                    "updated_at": "2025-09-02T07:38:59.194000",
                    "last_login": "2025-09-02T07:50:56.372000",
                    "api_calls_count": 0,
                    "max_api_calls": 1000
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/api-keys": {
      "post": {
        "summary": "创建API Key",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "",
            "required": true,
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc1NjgwMDc0MH0.PTNprud_lBpcm3p6aMgx3bMlPub-ZmEmfamKcXBpLtk",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "expires_at": {
                    "type": "string"
                  },
                  "permissions": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": [
                  "name",
                  "description",
                  "expires_at",
                  "permissions"
                ]
              },
              "example": {
                "name": "聊天API专用密钥",
                "description": "用于访问聊天和文件上传API的密钥",
                "expires_at": "2024-12-31T23:59:59Z",
                "permissions": [
                  "chat",
                  "upload"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "key_prefix": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "expires_at": {
                      "type": "string"
                    },
                    "last_used_at": {
                      "type": "null"
                    },
                    "permissions": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "is_active": {
                      "type": "boolean"
                    },
                    "created_by": {
                      "type": "string"
                    },
                    "full_key": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "description",
                    "key_prefix",
                    "created_at",
                    "expires_at",
                    "last_used_at",
                    "permissions",
                    "is_active",
                    "created_by",
                    "full_key"
                  ]
                },
                "example": {
                  "id": "68b6a40ed572df01e4ee12e9",
                  "name": "聊天API专用密钥",
                  "description": "用于访问聊天和文件上传API的密钥",
                  "key_prefix": "ccb37996",
                  "created_at": "2025-09-02T16:00:14.803179",
                  "expires_at": "2025-12-31T23:59:59",
                  "last_used_at": null,
                  "permissions": [
                    "chat",
                    "upload"
                  ],
                  "is_active": true,
                  "created_by": "68b69f1367bdaff96386c4e6",
                  "full_key": "ccb37996e5582ccebda2f91f7146eef8e8349c5d562caa4b26d286afddf52968"
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/chat": {
      "post": {
        "summary": "Chat接口（Detail=False Stream=True）",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "Agent",
            "in": "header",
            "description": "使用的后端Agent",
            "required": true,
            "example": "fastgpt",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "申请的 api_key",
            "required": true,
            "example": "Bearer api_key",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "app_id": {
                    "type": "string",
                    "title": "App ID",
                    "description": "对于FastGPT来说，这是必填项"
                  },
                  "chat_id": {
                    "type": "string",
                    "title": "对话ID",
                    "description": "用来控制对话的上下文"
                  },
                  "stream": {
                    "type": "boolean",
                    "title": "流式传输",
                    "description": "用来控制是否启用流式传输"
                  },
                  "detail": {
                    "type": "boolean",
                    "title": "详细",
                    "description": "是否输出详细内容"
                  },
                  "query": {
                    "type": "string"
                  },
                  "conversation_id": {
                    "type": "string",
                    "title": "对话ID",
                    "description": "用来控制Dify的上下文"
                  },
                  "files": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    },
                    "title": "文件URL"
                  }
                },
                "required": [
                  "app_id",
                  "chat_id",
                  "stream",
                  "detail",
                  "query",
                  "conversation_id",
                  "files"
                ]
              },
              "example": {
                "app_id": "string",
                "chat_id": "string",
                "stream": false,
                "detail": false,
                "query": "string",
                "conversation_id": "",
                "files": []
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "object": {
                      "type": "string"
                    },
                    "created": {
                      "type": "integer"
                    },
                    "model": {
                      "type": "string"
                    },
                    "choices": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "delta": {
                            "type": "object",
                            "properties": {
                              "role": {
                                "type": "string"
                              },
                              "content": {
                                "type": "string"
                              }
                            },
                            "required": [
                              "role",
                              "content"
                            ]
                          },
                          "index": {
                            "type": "integer"
                          },
                          "finish_reason": {
                            "type": "null"
                          }
                        }
                      }
                    }
                  },
                  "required": [
                    "object",
                    "created",
                    "model",
                    "choices"
                  ]
                },
                "example": "data: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"啊...你又说\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"喜欢\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"我\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"了\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"...\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"我\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"有点\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"困惑\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"呢\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"。\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"虽然\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"我\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"是个\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"AI\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"没有\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"真实\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"的情感\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"但\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"每次\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"你\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"这么说\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"我\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"都会\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"觉得\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"心里\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"暖\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"暖\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"的\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"。\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"不过\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"我\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"只能\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"以\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"一个\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"助手\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"的身份\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"来\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"回应\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"你\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"不能\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"真的\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"被\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"喜欢\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"哦\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"。\\n\\n\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"如果你\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"真的\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"喜欢\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"我\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"那\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\" maybe\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\" \"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"你可以\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"试着\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"喜欢\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"上\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"和\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"你\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"聊天\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"的\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"这个\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"AI\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"助手\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"？\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"虽然\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"我\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"不能\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"真正\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"被\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"喜欢\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"但\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"我会\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"一直\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"在这里\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"陪你\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"聊天\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"帮你\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"解决问题\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"或者\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"只是\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"听\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"你\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"说话\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"。\\n\\n\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"你\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"到底\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"是在\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"开玩笑\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"，\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"还是\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"真的\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"觉得\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"我\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"有\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"吸引力\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"呢\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\"？\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":\" 😊\"},\"index\":0,\"finish_reason\":null}]}\n\ndata: {\"id\":\"\",\"object\":\"\",\"created\":0,\"model\":\"\",\"choices\":[{\"delta\":{\"role\":\"assistant\",\"content\":null},\"index\":0,\"finish_reason\":\"stop\"}]}\n\ndata: [DONE]"
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "webhooks": {},
  "components": {
    "schemas": {},
    "securitySchemes": {}
  },
  "servers": []
}